# Intro

In [1]:
import numpy as np
import warnings

main numpy array attributes:
- dtype
- ndim
- shape
- size

In [2]:
ints = np.array([[1, 2, 3], [4, 5, 6]])
print(f'Data type: {ints.dtype}')
print(f'Dimensionality: {ints.ndim}')
print(f'Shape: {ints.shape}')
print(f'Size: {ints.size}')

Data type: int64
Dimensionality: 2
Shape: (2, 3)
Size: 6


# Array data types

## Integers

In [10]:
integers_64 = np.array([1, 2, 3, 4, 5])
print(type(integers_64))
print(f'Data type of the array: {integers_64.dtype}')
# default array datatype for integers is int64

integers_64[0] = 2
print(integers_64)
integers_64[0] = 5.1   # will be truncated
print(integers_64)

<class 'numpy.ndarray'>
Data type of the array: int64
[2 2 3 4 5]
[5 2 3 4 5]


In [4]:
warnings.filterwarnings('ignore')

integers_8 = np.array(integers_64, np.int8)
print(f'Data type of the array: {integers_64.dtype}')

integers_8[0] = 127
print(integers_8)
overflow = np.array([127, 128, 129, 130], np.int8)
# conversion of out-of-bound integers is deprecated
print(overflow)

warnings.filterwarnings('default')

Data type of the array: int64
[127   2   3   4   5]
[ 127 -128 -127 -126]


In [5]:
print(integers_64.nbytes)
print(integers_8.nbytes)
# int8 array takes 8 times less memory than int64

40
5


## Floats

In [6]:
floats_64 = np.array([.1, .2, .3, .4, .5])
floats_64.dtype

dtype('float64')

In [7]:
# if the data is mixed, the datatype of the array will be the most general one
np_arr = np.array([1, .1, 2, 3, 4])
print(np_arr.dtype)
np_arr = np.array([1, 'asdf', .2, 3, 4])
print(np_arr.dtype)

float64
<U32


# Multidimensional arrays

In [41]:
arr_2_dim = np.array([[1, 2, 3], [8, 7, 6]])
print(arr_2_dim, end='\n\n')
print(f'Dimensions: {arr_2_dim.ndim}')

[[1 2 3]
 [8 7 6]]

Dimensions: 2


In [42]:
# change 3rd column
arr_2_dim[:, 2] = [300, 600]
arr_2_dim

array([[  1,   2, 300],
       [  8,   7, 600]])

In [43]:
print(f'Second column: {arr_2_dim[:, 1]}')
print(f'Second row, first column: {arr_2_dim[1,0]}')

Second column: [2 7]
Second row, first column: 8


In [44]:
arr_3_dim = np.array([arr_2_dim, arr_2_dim])
print(f'1st 2-dim array, second row, first column: {arr_3_dim[0,1,0]}')

1st 2-dim array, second row, first column: 8


# Generate arrays

## arange

In [11]:
print(np.arange(5))
print(np.arange(100, 105))
print(np.arange(100, 150, 10))
print(np.arange(150, 100, -10), end='\n\n')

[0 1 2 3 4]
[100 101 102 103 104]
[100 110 120 130 140]
[150 140 130 120 110]



## linspace

In [12]:
print(np.linspace(10, 20, 5)) # 5 samples, by default 50
print(np.linspace((1,3), (8, 12), 5)) # 2-dim

[10.  12.5 15.  17.5 20. ]
[[ 1.    3.  ]
 [ 2.75  5.25]
 [ 4.5   7.5 ]
 [ 6.25  9.75]
 [ 8.   12.  ]]


## random

### rand

In [64]:
print(np.random.rand(3), end='\n\n')   # 1-dim array
print(np.random.rand(3,2)) # 2-dim array

[0.50523672 0.38689265 0.79363745]

[[0.58000418 0.1622986 ]
 [0.70075235 0.96455108]
 [0.50000836 0.88952006]]


In [60]:
print(np.random.rand(3))
print(np.random.rand(3), end='\n\n')

# if we use fixed seed value, the generated values will be the same each time
np.random.seed(2)
print(np.random.rand(3))
print(np.random.rand(3))

[0.18443987 0.78533515 0.85397529]
[0.49423684 0.84656149 0.07964548]

[0.4359949  0.02592623 0.54966248]
[0.43532239 0.4203678  0.33033482]


### randint

In [62]:
print(np.random.randint(1, 10, 5), end='\n\n') # 5 integers between 1 and 10
print(np.random.randint(low=0, high=100, size=(3, 2))) # 3x2 array of integers between 0 and 100

[4 6 9 5 7]

[[95 83]
 [31 66]
 [80 52]]


### randn

In [59]:
# generate random values from the standard normal distribution
print(np.random.randn(3, 2)) 

[[-1.24528809 -1.05795222]
 [-0.90900761  0.55145404]
 [ 2.29220801  0.04153939]]


## zeros/ones

In [12]:
print(np.zeros(5))
print(np.zeros((5,3), dtype=int))

[0. 0. 0. 0. 0.]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [13]:
print(np.ones(5))
print(np.ones((5,3), dtype=int))

[1. 1. 1. 1. 1.]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


## empty/fill/full

In [14]:
arr = np.empty(5, dtype=int)
print(arr, end='\n\n')

arr.fill(88)
print(arr)

[4607182418800017408 4607182418800017408 4607182418800017408
 4607182418800017408 4607182418800017408]

[88 88 88 88 88]


In [9]:
print(np.full(5, 2.5), end='\n\n')

arr_5x3 = np.full((5,3), 'a')
print(arr_5x3)
print(arr_5x3.shape, end='\n\n')

arr_2x2x2 = np.full((2,2,2), 88)
print(arr_2x2x2)
print(arr_2x2x2.shape, end='\n\n')

[2.5 2.5 2.5 2.5 2.5]

[['a' 'a' 'a']
 ['a' 'a' 'a']
 ['a' 'a' 'a']
 ['a' 'a' 'a']
 ['a' 'a' 'a']]
(5, 3)

[[[88 88]
  [88 88]]

 [[88 88]
  [88 88]]]
(2, 2, 2)



# Manipulate arrays

## insert / append / delete

In [16]:
arr = np.array([1, 2, 3])

print(np.insert(arr, 0, 111))
print(np.append(arr, 222))
print(np.delete(arr, 2))
print(arr)

[111   1   2   3]
[  1   2   3 222]
[1 2]
[1 2 3]


## sort

In [17]:
arr = np.array([[2, 3, 1], [5, 6, 4]])
print(np.sort(arr))

[[1 2 3]
 [4 5 6]]


## copy/view

In [18]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr_copy = arr.copy()
arr_copy[0][0] = 111
print(arr)
print(arr_copy)
print(arr_copy.base)

[[1 2 3]
 [4 5 6]]
[[111   2   3]
 [  4   5   6]]
None


In [19]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr_view = arr.view()
arr_view[0][0] = 111
print(arr)
print(arr_view)
print(arr_view.base)

[[111   2   3]
 [  4   5   6]]
[[111   2   3]
 [  4   5   6]]
[[111   2   3]
 [  4   5   6]]


## reshape/flatten/ravel

In [20]:
arr = np.arange(1, 7)
print(arr)
print(np.reshape(arr, (2, 3)))
print(arr.reshape(3, 2, 1))
print(arr)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]
[1 2 3 4 5 6]


In [21]:
# flattening with reshape
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(np.reshape(arr, -1))
print(arr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [22]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

# flattening with flatten creates a copy
arr_flatten = arr.flatten()
arr_flatten[3] = 444
print(arr_flatten)
print(arr)

[[1 2 3]
 [4 5 6]]
[  1   2   3 444   5   6]
[[1 2 3]
 [4 5 6]]


In [23]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

# flattening with ravel creates a view
arr_ravel = arr.ravel()
arr_ravel[3] = 444
print(arr_ravel)
print(arr)

[[1 2 3]
 [4 5 6]]
[  1   2   3 444   5   6]
[[  1   2   3]
 [444   5   6]]


## indexing/slicing

In [24]:
arr = np.reshape(np.arange(2*3*4), (2, 3, 4))
print(arr, end='\n\n\n')
print(arr[1,0])
print(arr[1,0,0])
print(arr[1,-1,-1])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


[12 13 14 15]
12
23


In [25]:
arr = np.reshape(np.arange(2*3*4), (2, 3, 4))
print(arr, end='\n\n\n')
print(arr[:, :, 3:], end='\n\n\n')
print(arr[1:, 1:])


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


[[[ 3]
  [ 7]
  [11]]

 [[15]
  [19]
  [23]]]


[[[16 17 18 19]
  [20 21 22 23]]]


## join

In [26]:
arr_1 = np.array([[1, 2, 3], [4, 5, 6]])
arr_2 = np.array([[7, 8, 9], [10, 11, 12]])
print(np.concatenate((arr_1, arr_2)), end='\n\n')
print(np.concatenate((arr_1, arr_2), axis=1), end='\n\n')

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]



In [27]:
# stack joins arrays along new axis
arr_1 = np.array([[1, 2, 3], [4, 5, 6]])
arr_2 = np.array([[7, 8, 9], [10, 11, 12]])
print(np.stack((arr_1, arr_2)))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [28]:
arr_1 = np.array([[1, 2, 3], [4, 5, 6]])
arr_2 = np.array([[7, 8, 9], [10, 11, 12]])
print(np.hstack((arr_1, arr_2)), end='\n\n')
print(np.vstack((arr_1, arr_2)))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## split

In [29]:
arr = np.arange(9)
print(arr)
print(np.array_split(arr, 3))
print(np.array_split(arr, 4))

[0 1 2 3 4 5 6 7 8]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [30]:
arr = np.array([[1, 2], [3, 4]])
print(arr, end='\n\n')
print(np.hsplit(arr, 2), end='\n\n')
print(np.vsplit(arr, 2))

[[1 2]
 [3 4]]

[array([[1],
       [3]]), array([[2],
       [4]])]

[array([[1, 2]]), array([[3, 4]])]
