In [2]:
import numpy as np
from numpy import linalg as lng
from IPython.display import display, Math

# Functions and Operations

## Element-wise operations

In [12]:
a = np.arange(1, 5)
b = np.arange(5, 9)
print('a', a)
print('b', b, end='\n\n')
print('+', a+b) # np.add(a, b)
print('-', b-a) # np.subtract(b, a)
print('*', a*b) # np.multiply(a, b)
print('÷', b/a, end='\n\n') # np.divide(b, a)

print('remainders of b÷a', np.mod(b, a))

a [1 2 3 4]
b [5 6 7 8]

+ [ 6  8 10 12]
- [4 4 4 4]
* [ 5 12 21 32]
÷ [5.         3.         2.33333333 2.        ]

remainders of b÷a [0 0 1 0]


In [13]:
a = np.arange(1, 5)
e = np.arange(1, 5)
print('a', a)
print('e', e, end='\n\n')
print('a^2', a^2)
print('a^e', a**e) # np.power(a, e)
print('√a', np.sqrt(a))

a [1 2 3 4]
e [1 2 3 4]

a^2 [3 0 1 6]
a^e [  1   4  27 256]
√a [1.         1.41421356 1.73205081 2.        ]


In [9]:
a = np.array([1, 100, 200, 300])
b = np.array([100, 1, 1, 1])
print(a >= b, end='\n\n')
print(a[a > 2]) # apply boolean mask

[False  True  True  True]

[100 200 300]


## Broadcasting

If during arithmetic operation arrays have different shape, the smaller array is broadcast across the larger array so that their shapes become compatible.

In [4]:
a = np.arange(1, 10).reshape(3, 3)
b = np.arange(1, 4)
print('a', a, end='\n\n')
print('b', b, end='\n\n')
print(f'Shape of a: {a.shape} \nShape of b: {b.shape}', end='\n\n')
print('a+b', a+b)

a [[1 2 3]
 [4 5 6]
 [7 8 9]]

b [1 2 3]

Shape of a: (3, 3) 
Shape of b: (3,)

a+b [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [5]:
a = np.arange(1, 10).reshape(3, 3)
b = np.arange(1, 3) # can't be broadcasted
print('a', a, end='\n\n')
print('b', b, end='\n\n')
print(f'Shape of a: {a.shape} \nShape of b: {b.shape}', end='\n\n')

try:
    a+b
except Exception as e:
    print(e)


a [[1 2 3]
 [4 5 6]
 [7 8 9]]

b [1 2]

Shape of a: (3, 3) 
Shape of b: (2,)

operands could not be broadcast together with shapes (3,3) (2,) 


## Aggregate functions

In [6]:
arr = np.arange(10, 100, 10).reshape(3, 3)
print(arr)
print('Sum of all elements:', arr.sum())
print('Sum of columns:', arr.sum(axis=0))
print('Sum of rows:', arr.sum(axis=1))


[[10 20 30]
 [40 50 60]
 [70 80 90]]
Sum of all elements: 450
Sum of columns: [120 150 180]
Sum of rows: [ 60 150 240]


In [7]:
arr = np.arange(10, 100, 10).reshape(3, 3)
print(arr)
print('Product of all elements:', arr.prod())
print('Product of columns:', arr.prod(axis=0))
print('Product of rows:', arr.prod(axis=1))

[[10 20 30]
 [40 50 60]
 [70 80 90]]
Product of all elements: 362880000000000
Product of columns: [ 28000  80000 162000]
Product of rows: [  6000 120000 504000]


In [8]:
arr = np.arange(10, 100, 10).reshape(3, 3)
print('average:', np.average(arr))
print('mean:', np.mean(arr))
print('min:', np.min(arr))
print('max:', np.max(arr))
print('std:', np.std(arr))

average: 50.0
mean: 50.0
min: 10
max: 90
std: 25.81988897471611


In [9]:
arr = np.array([[1, 1, 2], [1, 1, 2], [4, 4, 5]])
print(arr, end='\n\n')
print('unique:', np.unique(arr))
print('unique with indexes:\n', np.unique(arr, return_index=True))
print('unique with columns:\n', np.unique(arr, return_counts=True))
print('unique rows:\n', np.unique(arr, axis=0))
print('unique columns:\n', np.unique(arr, axis=1))

[[1 1 2]
 [1 1 2]
 [4 4 5]]

unique: [1 2 4 5]
unique with indexes:
 (array([1, 2, 4, 5]), array([0, 2, 6, 8]))
unique with columns:
 (array([1, 2, 4, 5]), array([4, 2, 2, 1]))
unique rows:
 [[1 1 2]
 [4 4 5]]
unique columns:
 [[1 2]
 [1 2]
 [4 5]]


## transpose/moveaxis/swapaxis

In [10]:
# reshape remakes the array by the inputs, transpose swaps rows and columns of an array (inverts axes)
arr_3x4 = np.arange(12).reshape(3, 4)
print(arr_3x4)
print(np.transpose(arr_3x4), end='\n\n')

arr_3x2 = np.arange(6).reshape(3, 2)
print(arr_3x2)
print(np.transpose(arr_3x2, (1,0)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

[[0 1]
 [2 3]
 [4 5]]
[[0 2 4]
 [1 3 5]]


In [11]:
# moveaxis returns an array with moved axes
arr = np.arange(24).reshape(2, 3, 4)
print(arr, end='\n\n\n')
print(np.moveaxis(arr, 0, -1))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]


In [12]:
# swapaxex interchanges two axes of an array
arr = np.arange(24).reshape(2, 3, 4)
print(arr, end='\n\n\n')
print(np.swapaxes(arr, 0, 2))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]


## reverse

In [13]:
arr = np.arange(9).reshape(3, 3)
print(arr, end='\n\n')
print(np.flip(arr), end='\n\n')
print(np.flip(arr, 1), end='\n\n') # 1 number of axis

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[8 7 6]
 [5 4 3]
 [2 1 0]]

[[2 1 0]
 [5 4 3]
 [8 7 6]]



## dot

In [14]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

print('Dot product is commutative:', np.dot(a,b)==np.dot(b,a))
display(Math('a⋅b = b⋅a'))
print('Dot product is distributive over addition:', np.dot(a,b+c)==np.dot(a,b)+np.dot(a,c))
display(Math('a⋅(b+c) = a⋅b+a⋅c'))


Dot product is commutative: True


<IPython.core.display.Math object>

Dot product is distributive over addition: True


<IPython.core.display.Math object>

## norm

In [15]:
a = np.array([4, 4, 2])
print(a)

# vector magnitude (norm)
display(Math(f'||ā|| = {lng.norm(a)}'))

[4 4 2]


<IPython.core.display.Math object>